name: auto_data_generator
description: Auto-generate dart data classes
version: 0.0.1
author: Paul DeMarco
homepage: https://www.github.com/pauldemarco/auto_data

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  auto_data:
    path: ../auto_data
  build: ^1.0.0
  source_gen: ^0.9.4+1

dev_dependencies:
  build_runner: ^1.0.0
  test: