name: auto_data_generator
description: >
  Automatically generate simple data class files for Dart.
  This is the dev dependency.
version: 0.0.2
author: Paul DeMarco <paulmdemarco@gmail.com>
homepage: https://www.github.com/pauldemarco/auto_data

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  auto_data: ^0.0.2
  build: ^1.0.0
  source_gen: ^0.9.4+1

dev_dependencies:
  build_runner: ^1.0.0
  test: