name: auto_data
description: >
  Automatically generate simple data class files for Dart.
  This is the runtime dependency.
version: 0.0.1
author: Paul DeMarco <paulmdemarco@gmail.com>
homepage: https://www.github.com/pauldemarco/auto_data

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: